{
 "title": "ICMP PING",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dest",
    "label": "dest",
    "query": {
     "query": "label_values(pingJitter,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pingJitter{instance=~\"$dest\"}",
     "legendFormat": "{{pinger}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pingLatencyAvg{instance=~\"$dest\"}",
     "legendFormat": "{{pinger}}-{{instance}}"
    }
   ]
  },
  {
   "title": "PacketLoss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pingPacketLoss{instance=~\"$dest\"}",
     "legendFormat": "{{pinger}}-{{instance}}"
    }
   ]
  },
  {
   "title": "PacketLossPerc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pingPacketLossPerc{instance=~\"$dest\"}",
     "legendFormat": "{{pinger}}-{{instance}}"
    }
   ]
  }
 ]
}